version: '3'
services:
  react-app:
    build: .
    ports:
      - "3001:3000"   # Host port 3001, container port 3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0

